apiVersion: v1
kind: Service
metadata:
  name: broker
spec:
  type: LoadBalancer
  selector:
    app: broker
  ports:
    - name: ws1
      port: 5001
      targetPort: 5001
    - name: ws2
      port: 5002
      targetPort: 5002
    - name: ws3
      port: 5003
      targetPort: 5003
