apiVersion: v1
kind: Service
metadata:
  name: wallet
spec:
  type: LoadBalancer
  selector:
    app: wallet
  ports:
    - name: ws1
      port: 7001
      targetPort: 7001
    - name: ws2
      port: 7002
      targetPort: 7002
